### PR TITLE
Added Comparison operators

### PR DESCRIPTION
**Pull request by MohamedDanis**
I have added comparison operators,which will be useful for beginners.And changed "Types in python" to "Datatypes in python"

### CODE REVIEW

**Comment by Sarveshmrao** [comment]
Great work thanks! Accepted!

**Comment by MohamedDanis** [comment]
is your repository is eligible for hacktoberfest...and digital ocean site shows invalid repository

**Comment by Sarveshmrao** [comment]
@MohamedDanis can you check now?

**Comment by MohamedDanis** [comment]
it worked

**Pull request merged**
